gitlabhq-master/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'api/api'

Rails.application.routes.draw do
  if Gitlab::Sherlock.enabled?
    namespace :sherlock do
      resources :transactions, only: [:index, :show] do
        resources :queries, only: [:show]
        resources :file_samples, only: [:show]

        collection do
          delete :destroy_all
        end
      end
    end
  end

  namespace :ci do
    # CI API
    Ci::API::API.logger Rails.logger
    mount Ci::API::API => '/api'

    resource :lint, only: [:show, :create]

    resources :projects do
      member do
        get :status, to: 'projects#badge'
        get :integration
      end
    end

    root to: 'projects#index'
  end

  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications',
                authorizations: 'oauth/authorizations'
  end

  # Autocomplete
  get '/autocomplete/users' => 'autocomplete#users'
  get '/autocomplete/users/:id' => 'autocomplete#user'


  # Search
  get 'search' => 'search#show'
  get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: '/admin/sidekiq', as: :sidekiq
  end

  # Enable Grack support
  mount Grack::AuthSpawner, at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post, :put]

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }
  get 'help/shortcuts'
  get 'help/ui'               => 'help#ui'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get 'raw'
    end
  end

  get '/s/:username' => 'snippets#index', as: :user_snippets, constraints: { username: /.*/ }

  #
  # Invites
  #

  resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
    member do
      post :accept
      match :decline, via: [:get, :post]
    end
  end

  resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
    member do
      get :unsubscribe
    end
  end

  # Spam reports
  resources :abuse_reports, only: [:new, :create]

  #
  # Import
  #
  namespace :import do
    resource :github, only: [:create, :new], controller: :github do
      get :status
      get :callback
      get :jobs
    end

    resource :gitlab, only: [:create, :new], controller: :gitlab do
      get :status
      get :callback
      get :jobs
    end

    resource :bitbucket, only: [:create, :new], controller: :bitbucket do
      get :status
      get :callback
      get :jobs
    end

    resource :gitorious, only: [:create, :new], controller: :gitorious do
      get :status
      get :callback
      get :jobs
    end

    resource :google_code, only: [:create, :new], controller: :google_code do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end

    resource :fogbugz, only: [:create, :new], controller: :fogbugz do
      get :status
      post :callback
      get :jobs

      get   :new_user_map,    path: :user_map
      post  :create_user_map, path: :user_map
    end
  end

  #
  # Uploads
  #

  scope path: :uploads do
    # Note attachments and User/Group/Project avatars
    get ":model/:mounted_as/:id/:filename",
        to:           "uploads#show",
        constraints:  { model: /note|user|group|project/, mounted_as: /avatar|attachment/, filename: /[^\/]+/ }

    # Project markdown uploads
    get ":namespace_id/:project_id/:secret/:filename",
      to:           "projects/uploads#show",
      constraints:  { namespace_id: /[a-zA-Z.0-9_\-]+/, project_id: /[a-zA-Z.0-9_\-]+/, filename: /[^\/]+/ }
  end

  # Redirect old note attachments path to new uploads path.
  get "files/note/:id/:filename",
    to:           redirect("uploads/note/attachment/%{id}/%{filename}"),
    constraints:  { filename: /[^\/]+/ }

  #
  # Explore area
  #
  namespace :explore do
    resources :projects, only: [:index] do
      collection do
        get :trending
        get :starred
      end
    end

    resources :groups, only: [:index]
    resources :snippets, only: [:index]
    root to: 'projects#trending'
  end

  # Compatibility with old routing
  get 'public' => 'explore/projects#index'
  get 'public/projects' => 'explore/projects#index'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      resources :keys, only: [:show, :destroy]
      resources :identities, except: [:show]

      delete 'stop_impersonation' => 'impersonation#destroy', on: :collection

      member do
        get :projects
        get :keys
        get :groups
        put :team_update
        put :block
        put :unblock
        put :unlock
        put :confirm
        post 'impersonate' => 'impersonation#create'
        patch :disable_two_factor
        delete 'remove/:email_id', action: 'remove_email', as: 'remove_email'
      end
    end

    resources :abuse_reports, only: [:index, :destroy]
    resources :applications

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :members_update
      end
    end

    resources :deploy_keys, only: [:index, :new, :create, :destroy]

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :edit, :create, :update, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :namespaces, path: '/projects', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
      root to: 'projects#index', as: :projects

      resources(:projects,
                path: '/',
                constraints: { id: /[a-zA-Z.0-9_\-]+/ },
                only: [:index, :show]) do
        root to: 'projects#show'

        member do
          put :transfer
        end

        resources :runner_projects
      end
    end

    resource :application_settings, only: [:show, :update] do
      resources :services
      put :reset_runners_token
    end

    resources :labels

    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        get :resume
        get :pause
      end
    end

    resources :builds, only: :index do
      collection do
        post :cancel_all
      end
    end

    root to: 'dashboard#index'
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :audit_log
      get :applications

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update] do
        member do
          delete :unlink
        end
      end
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resource :preferences, only: [:show, :update]
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
      resource :two_factor_auth, only: [:new, :create, :destroy] do
        member do
          post :codes
          patch :skip
        end
      end
    end
  end

  get 'u/:username/calendar' => 'users#calendar', as: :user_calendar,
      constraints: { username: /.*/ }

  get 'u/:username/calendar_activities' => 'users#calendar_activities', as: :user_calendar_activities,
      constraints: { username: /.*/ }

  get '/u/:username' => 'users#show', as: :user,
      constraints: { username: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }

  #
  # Dashboard Area
  #
  resource :dashboard, controller: 'dashboard', only: [] do
    get :issues
    get :merge_requests
    get :activity

    scope module: :dashboard do
      resources :milestones, only: [:index, :show]

      resources :groups, only: [:index]
      resources :snippets, only: [:index]

      resources :projects, only: [:index] do
        collection do
          get :starred
        end
      end
    end

    root to: "dashboard/projects#index"
  end

  #
  # Groups Area
  #
  resources :groups, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }  do
    member do
      get :issues
      get :merge_requests
      get :projects
    end

    scope module: :groups do
      resources :group_members, only: [:index, :create, :update, :destroy] do
        post :resend_invite, on: :member
        delete :leave, on: :collection
      end

      resource :avatar, only: [:destroy]
      resources :milestones, constraints: { id: /[^\/]+/ }, only: [:index, :show, :update, :new, :create]
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:index, :new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords, sessions: :sessions, confirmations: :confirmations }

  devise_scope :user do
    get '/users/auth/:provider/omniauth_error' => 'omniauth_callbacks#omniauth_error', as: :omniauth_error
  end

  root to: "root#index"

  #
  # Project Area
  #
  resources :namespaces, path: '/', constraints: { id: /[a-zA-Z.0-9_\-]+/ }, only: [] do
    resources(:projects, constraints: { id: /[a-zA-Z.0-9_\-]+(?<!\.atom)/ }, except:
              [:new, :create, :index], path: "/") do
      member do
        put :transfer
        delete :remove_fork
        post :archive
        post :unarchive
        post :housekeeping
        post :toggle_star
        post :markdown_preview
        get :autocomplete_sources
        get :activity
      end

      scope module: :projects do
        # Blob routes:

gitlabhq-master/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :project, only: [:show, :transfer]
  before_action :group, only: [:show, :transfer]
  before_action :repository, only: [:show, :transfer]

  def index
    @projects = Project.all
    @projects = @projects.in_namespace(params[:namespace_id]) if params[:namespace_id].present?
    @projects = @projects.where("visibility_level IN (?)", params[:visibility_levels]) if params[:visibility_levels].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.non_archived unless params[:with_archived].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.sort(@sort = params[:sort])
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(PER_PAGE)
  end

  def show
    if @group
      @group_members = @group.members.order("access_level DESC").page(params[:group_members_page]).per(PER_PAGE)
    end

    @project_members = @project.project_members.page(params[:project_members_page]).per(PER_PAGE)
  end

  def transfer
    namespace = Namespace.find_by(id: params[:new_namespace_id])
    ::Projects::TransferService.new(@project, current_user, params.dup).execute(namespace)

    @project.reload
    redirect_to admin_namespace_project_path(@project.namespace, @project)
  end

  protected

  def project
    @project = Project.find_with_namespace(
      [params[:namespace_id], '/', params[:id]].join('')
    )
    @project || render_404
  end

  def group
    @group ||= @project.group
  end
end

gitlabhq-master/app/controllers/ci/projects_controller.rb
module Ci
  class ProjectsController < Ci::ApplicationController
    before_action :project, except: [:index]
    before_action :authenticate_user!, except: [:index, :build, :badge]
    before_action :authorize_access_project!, except: [:index, :badge]
    before_action :no_cache, only: [:badge]
    protect_from_forgery

    def show
      # Temporary compatibility with CI badges pointing to CI project page
      redirect_to namespace_project_path(project.namespace, project)
    end

    # Project status badge
    # Image with build status for sha or ref
    def badge
      image = Ci::ImageForBuildService.new.execute(@project, params)

      send_file image.path, filename: image.name, disposition: 'inline', type:"image/svg+xml"
    end

    protected

    def project
      @project ||= Project.find_by(ci_id: params[:id].to_i)
    end

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end
  end
end

gitlabhq-master/app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::ApplicationController
  before_action :event_filter

  def index
    @projects = current_user.authorized_projects.sorted_by_activity.non_archived
    @projects = @projects.includes(:namespace)
    @last_push = current_user.recent_push

    respond_to do |format|
      format.html
      format.atom do
        event_filter
        load_events
        render layout: false
      end
    end
  end

  def starred
    @projects = current_user.starred_projects
    @projects = @projects.includes(:namespace, :forked_from_project, :tags)
    @projects = @projects.sort(@sort = params[:sort])
    @last_push = current_user.recent_push
    @groups = []

    respond_to do |format|
      format.html

      format.json do
        load_events
        pager_json("events/_events", @events.count)
      end
    end
  end

  private

  def load_events
    @events = Event.in_projects(@projects)
    @events = @event_filter.apply_filter(@events).with_associations
    @events = @events.limit(20).offset(params[:offset] || 0)
  end
end

gitlabhq-master/app/controllers/explore/projects_controller.rb
class Explore::ProjectsController < Explore::ApplicationController
  def index
    @projects = ProjectsFinder.new.execute(current_user)
    @tags = @projects.tags_on(:tags)
    @projects = @projects.tagged_with(params[:tag]) if params[:tag].present?
    @projects = @projects.where(visibility_level: params[:visibility_level]) if params[:visibility_level].present?
    @projects = @projects.non_archived
    @projects = @projects.search(params[:search]) if params[:search].present?
    @projects = @projects.sort(@sort = params[:sort])
    @projects = @projects.includes(:namespace).page(params[:page]).per(PER_PAGE)
  end

  def trending
    @trending_projects = TrendingProjectsFinder.new.execute(current_user)
    @trending_projects = @trending_projects.non_archived
    @trending_projects = @trending_projects.page(params[:page]).per(PER_PAGE)
  end

  def starred
    @starred_projects = ProjectsFinder.new.execute(current_user)
    @starred_projects = @starred_projects.reorder('star_count DESC')
    @starred_projects = @starred_projects.page(params[:page]).per(PER_PAGE)
  end
end

gitlabhq-master/app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_action :project
  before_action :repository
  layout 'project'

  def authenticate_user!
    # Restrict access to Projects area only
    # for non-signed users
    if !current_user
      id = params[:project_id] || params[:id]
      project_with_namespace = "#{params[:namespace_id]}/#{id}"
      @project = Project.find_with_namespace(project_with_namespace)

      return if @project && @project.public?
    end

    super
  end

  def require_branch_head
    unless @repository.branch_names.include?(@ref)
      redirect_to(
        namespace_project_tree_path(@project.namespace, @project, @ref),
        notice: "This action is not allowed unless you are on a branch"
      )
    end
  end

  private

  def builds_enabled
    return render_404 unless @project.builds_enabled?
  end
end

gitlabhq-master/app/controllers/projects/artifacts_controller.rb
class Projects::ArtifactsController < Projects::ApplicationController
  layout 'project'
  before_action :authorize_read_build_artifacts!

  def download
    unless artifacts_file.file_storage?
      return redirect_to artifacts_file.url
    end

    unless artifacts_file.exists?
      return render_404
    end

    send_file artifacts_file.path, disposition: 'attachment'
  end

  def browse
    return render_404 unless build.artifacts?

    directory = params[:path] ? "#{params[:path]}/" : ''
    @entry = build.artifacts_metadata_entry(directory)

    return render_404 unless @entry.exists?
  end

  def file
    entry = build.artifacts_metadata_entry(params[:path])

    if entry.exists?
      render json: { archive: build.artifacts_file.path,
                     entry: Base64.encode64(entry.path) }
    else
      render json: {}, status: 404
    end
  end

  private

  def build
    @build ||= project.builds.unscoped.find_by!(id: params[:build_id])
  end

  def artifacts_file
    @artifacts_file ||= build.artifacts_file
  end

  def authorize_read_build_artifacts!
    unless can?(current_user, :read_build_artifacts, @project)
      if current_user.nil?
        return authenticate_user!
      else
        return render_404
      end
    end
  end
end

gitlabhq-master/app/views/projects/_activity.html.haml
.nav-block.activity-filter-block
  - if current_user
    .controls
      = link_to namespace_project_path(@project.namespace, @project, format: :atom, private_token: current_user.private_token), title: "Feed", class: 'btn rss-btn' do
        %i.fa.fa-rss

  = render 'shared/event_filter'
.content_list{:"data-href" => activity_project_path(@project)}
= spinner

:javascript
  new Activities();

gitlabhq-master/app/views/projects/_errors.html.haml
- if @project.errors.any?
  .alert.alert-danger
    %button{ type: "button", class: "close", "data-dismiss" => "alert"} &times;
    = @project.errors.full_messages.first

gitlabhq-master/app/views/projects/_files.html.haml
#tree-holder.tree-holder.clearfix
  .nav-block
    = render 'projects/tree/tree_header', tree: @tree

  = render 'projects/tree/tree_content', tree: @tree

gitlabhq-master/app/views/projects/_find_file_link.html.haml
= link_to namespace_project_find_file_path(@project.namespace, @project, @ref), class: 'btn btn-grouped shortcuts-find-file', rel: 'nofollow' do
  = icon('search')
  %span Find File

gitlabhq-master/app/views/projects/_gitlab_import_modal.html.haml
%div#gitlab_import_modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{href: "#", "data-dismiss" => "modal"} ×
        %h3 Import projects from GitLab.com
      .modal-body
        To enable importing projects from GitLab.com,
        - if current_user.admin?
          as administrator you need to configure
        - else
          ask your GitLab administrator to configure
        == #{link_to 'OAuth integration', help_page_path("integration", "gitlab")}.

gitlabhq-master/app/views/projects/_home_panel.html.haml
- empty_repo = @project.empty_repo?
.project-home-panel.cover-block.clearfix{:class => ("empty-project" if empty_repo)}
  .project-identicon-holder
    = project_icon(@project, alt: '', class: 'project-avatar avatar s90')
  .project-home-desc
    %h1= @project.name
    - if @project.description.present?
      = markdown(@project.description, pipeline: :description)

    - if forked_from_project = @project.forked_from_project
      %p
        Forked from
        = link_to project_path(forked_from_project) do
          = forked_from_project.namespace.try(:name)
  .cover-controls.left
    .visibility-level-label.has_tooltip{title: project_visibility_level_description(@project.visibility_level), data: { container: 'body' } }
      = visibility_level_icon(@project.visibility_level, fw: false)
      = visibility_level_label(@project.visibility_level)

  .cover-controls
    - if current_user
      = link_to namespace_project_path(@project.namespace, @project, format: :atom, private_token: current_user.private_token), class: 'btn btn-gray' do
        = icon('rss')
      - access = user_max_access_in_project(current_user.id, @project)
      - can_edit = can?(current_user, :admin_project, @project)
      - if access || can_edit
        %span.dropdown.project-settings-dropdown
          %a.dropdown-new.btn.btn-gray#project-settings-button{href: '#', 'data-toggle' => 'dropdown'}
            = icon('cog')
            = icon('angle-down')
          %ul.dropdown-menu.dropdown-menu-right
            - if can_edit
              %li
                = link_to edit_project_path(@project) do
                  Edit Project
            - if access
              %li
                = link_to leave_namespace_project_project_members_path(@project.namespace, @project),
                  data: { confirm: leave_project_message(@project) }, method: :delete, title: 'Leave project' do
                  Leave Project

  .project-repo-buttons
    .split-one.count-buttons
      = render 'projects/buttons/star'
      = render 'projects/buttons/fork'

    .clone-row
      .project-clone-holder
        = render "shared/clone_panel"

      .split-repo-buttons
        .btn-group.pull-left
          = render "projects/buttons/download"
          = render 'projects/buttons/dropdown'

      = render 'projects/buttons/notifications'

:javascript
  new Star();

gitlabhq-master/app/views/projects/_readme.html.haml
- if readme = @repository.readme
  %article.readme-holder
    .pull-right
      - if can?(current_user, :push_code, @project)
        = link_to icon('pencil'), namespace_project_edit_blob_path(@project.namespace, @project, tree_join(@repository.root_ref, readme.name)), class: 'light edit-project-readme'
    .file-content.wiki
      = cache(readme_cache_key) do
        = render_readme(readme)
- else
  .gray-content-block.second-block.center
    %h3.page-title
      This project does not have README yet
    - if can?(current_user, :push_code, @project)
      %p
        A
        %code README
        file contains information about other files in a repository and is commonly
        distributed with computer software, forming part of its documentation.
      %p
        We recommend you to
        = link_to "add README", new_readme_path, class: 'underlined-link'
        file to the repository and GitLab will render it here instead of this message.

gitlabhq-master/app/views/projects/_zen.html.haml
.zennable
  .zen-backdrop
    - classes << ' js-gfm-input js-autosize markdown-area'
    - if defined?(f) && f
      = f.text_area attr, class: classes
    - else
      = text_area_tag attr, nil, class: classes
    %a.js-zen-enter(tabindex="-1" href="#")
      = icon('expand')
      Edit in fullscreen
    %a.js-zen-leave(tabindex="-1" href="#")
      = icon('compress')

gitlabhq-master/app/views/projects/activity.html.haml
- page_title "Activity"
- header_title project_title(@project, "Activity", activity_project_path(@project))

= render 'projects/last_push'

= render 'projects/activity'

gitlabhq-master/app/views/projects/empty.html.haml
- @no_container = true

= content_for :flash_message do
  - if current_user && can?(current_user, :download_code, @project)
    = render 'shared/no_ssh'
    = render 'shared/no_password'

= render "home_panel"

.gray-content-block.second-block.center
  %h3.page-title
    The repository for this project is empty
  - if can?(current_user, :push_code, @project)
    %p
      If you already have files you can push them using command line instructions below.
    %p
      Otherwise you can start with
      = link_to "adding README", new_readme_path, class: 'underlined-link'
      file to this project.

- if can?(current_user, :download_code, @project)
  %div{ class: container_class }
    .prepend-top-20
    .empty_wrapper
      %h3.page-title-empty
        Command line instructions
      %div.git-empty
        %fieldset
          %h5 Git global setup
          %pre.light-well
            :preserve
              git config --global user.name "#{h git_user_name}"
              git config --global user.email "#{h git_user_email}"

        %fieldset
          %h5 Create a new repository
          %pre.light-well
            :preserve
              git clone #{ content_tag(:span, default_url_to_repo, class: 'clone')}
              cd #{h @project.path}
              touch README.md
              git add README.md
              git commit -m "add README"
              git push -u origin master

        %fieldset
          %h5 Existing folder or Git repository
          %pre.light-well
            :preserve
              cd existing_folder
              git init
              git remote add origin #{ content_tag(:span, default_url_to_repo, class: 'clone')}
              git add .
              git commit
              git push -u origin master

          - if can? current_user, :remove_project, @project
            .prepend-top-20
              = link_to 'Remove project', [@project.namespace.becomes(Namespace), @project], data: { confirm: remove_project_message(@project)}, method: :delete, class: "btn btn-remove pull-right"

gitlabhq-master/app/views/projects/go_import.html.haml
!!! 5
%html
  %head
    - web_url = [Gitlab.config.gitlab.url, @namespace, @id].join('/')
    %meta{name: "go-import", content: "#{web_url.split('://')[1]} git #{web_url}.git"}

gitlabhq-master/app/views/projects/new.html.haml
- page_title    'New Project'
- header_title  "Projects", root_path

%h3.page-title
  New Project
%hr

.project-edit-container
  .project-edit-errors
    = render 'projects/errors'
  .project-edit-content

    = form_for @project, html: { class: 'new_project form-horizontal js-requires-input' } do |f|
      .form-group.project-name-holder
        = f.label :path, class: 'control-label' do
          Project path
        .col-sm-10
          .input-group
            - if current_user.can_select_namespace?
              .input-group-addon
                = root_url
              = f.select :namespace_id, namespaces_options(params[:namespace_id] || :current_user, display_path: true), {}, {class: 'select2', tabindex: 1}
              .input-group-addon
                \/
            - else
              .input-group-addon
                #{root_url}#{current_user.username}/
            = f.text_field :path, placeholder: "my-awesome-project", class: "form-control", tabindex: 2, autofocus: true, required: true

          - if current_user.can_create_group?
            .help-block
              Want to house several dependent projects under the same namespace?
              = link_to "Create a group", new_group_path

      - if import_sources_enabled?
        .project-import.js-toggle-container
          .form-group
            %label.control-label Import project from
            .col-sm-10
              - if github_import_enabled?
                - if github_import_configured?
                  = link_to status_import_github_path, class: 'btn import_github' do
                    %i.fa.fa-github
                    GitHub
                - else
                  = link_to '#', class: 'how_to_import_link btn import_github' do
                    %i.fa.fa-github
                    GitHub
                  = render 'github_import_modal'

              - if bitbucket_import_enabled?
                - if bitbucket_import_configured?
                  = link_to status_import_bitbucket_path, class: 'btn import_bitbucket', "data-no-turbolink" => "true" do
                    %i.fa.fa-bitbucket
                    Bitbucket
                - else
                  = link_to status_import_bitbucket_path, class: 'how_to_import_link btn import_bitbucket', "data-no-turbolink" => "true" do
                    %i.fa.fa-bitbucket
                    Bitbucket
                  = render 'bitbucket_import_modal'

              - if gitlab_import_enabled?
                - if gitlab_import_configured?
                  = link_to status_import_gitlab_path, class: 'btn import_gitlab' do
                    %i.fa.fa-heart
                    GitLab.com
                - else
                  = link_to status_import_gitlab_path, class: 'how_to_import_link btn import_gitlab' do
                    %i.fa.fa-heart
                    GitLab.com
                  = render 'gitlab_import_modal'

              - if gitorious_import_enabled?
                = link_to new_import_gitorious_path, class: 'btn import_gitorious' do
                  %i.icon-gitorious.icon-gitorious-small
                  Gitorious.org

              - if google_code_import_enabled?
                = link_to new_import_google_code_path, class: 'btn import_google_code' do
                  %i.fa.fa-google
                  Google Code

              - if fogbugz_import_enabled?
                = link_to new_import_fogbugz_path, class: 'btn import_fogbugz' do
                  %i.fa.fa-bug
                  Fogbugz

              - if git_import_enabled?
                = link_to "#", class: 'btn js-toggle-button import_git' do
                  %i.fa.fa-git
                  %span Any repo by URL

          .js-toggle-content.hide
            = render "shared/import_form", f: f

      .prepend-botton-10

      .form-group
        = f.label :description, class: 'control-label' do
          Description
          %span.light (optional)
        .col-sm-10
          = f.text_area :description, class: "form-control", rows: 3, maxlength: 250, tabindex: 3
      = render 'shared/visibility_level', f: f, visibility_level: default_project_visibility, can_change_visibility_level: true, form_model: @project

      .form-actions
        = f.submit 'Create project', class: "btn btn-create project-submit", tabindex: 4
        = link_to 'Cancel', dashboard_projects_path, class: 'btn btn-cancel'

.save-project-loader.hide
  .center
    %h2
      %i.fa.fa-spinner.fa-spin
      Creating project &amp; repository.
    %p Please wait a moment, this page will automatically refresh when ready.

:javascript
  $('.how_to_import_link').bind('click', function (e) {
    e.preventDefault();
    var import_modal = $(this).next(".modal").show();
  });
  $('.modal-header .close').bind('click', function() {
    $(".modal").hide();
  });

gitlabhq-master/app/views/projects/no_repo.html.haml
%h2
  %i.fa.fa-warning
  No repository

%p.slead
  The repository for this project does not exist.
  %br
  This means you can not push code until you create an empty repository or import existing one.
%hr

.no-repo-actions
  = link_to namespace_project_repository_path(@project.namespace, @project), method: :post, class: 'btn btn-primary' do
    Create empty bare repository

  %strong.prepend-left-10.append-right-10 or

  = link_to new_namespace_project_import_path(@project.namespace, @project), class: 'btn' do
    Import repository

- if can? current_user, :remove_project, @project
  .prepend-top-20
    = link_to 'Remove project', project_path(@project), data: { confirm: remove_project_message(@project)}, method: :delete, class: "btn btn-remove pull-right"

gitlabhq-master/app/views/projects/transfer.js.haml
:plain
    location.href = "#{edit_namespace_project_path(@project.namespace, @project)}";